import Head from "next/head";
import styles from "../styles/Home.module.css";
import { useEffect, useState } from "react";

export default function Home() {
  // 入力した値(ms)だけ遅れて返事をする処理
  const [time, setTime] = useState("");

  const submitHandle = async (e) => {
    e.preventDefault();
    await new Promise((resolve) => {
      setTimeout(() => {
        resolve();
      }, time);
    });

    console.log(`${time}msまってくれた？`);
  };

  const handleChangeTime = (e) => {
    setTime(e.target.value);
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>
      </main>

      <form>
        <input onChange={handleChangeTime} value={time} />
        <button onClick={submitHandle}>送る</button>
      </form>
    </div>
  );
}
